### ISSUE TITLE
Bottomsheet view width issue when calling another view controller

### ISSUE THREAD

**Issue by osmansoykan** [finn-no/BottomSheet#46]
Hi,
There is a situation like this that I can not find the reason.
Call the bottom sheet screen like this and screenshot first:

```
    private lazy var bottomSheetTransitioningDelegate = BottomSheetTransitioningDelegate(
        contentHeights: [.bottomSheetAutomatic, 200 ],
        startTargetIndex: 0
    )
```

```
 let mViewcontroller = destination(.selectAccount) as! AccountListViewController
        mViewcontroller.contentHeight = 200
        mViewcontroller.transitioningDelegate = bottomSheetTransitioningDelegate
        mViewcontroller.modalPresentationStyle = .custom
        present(mViewcontroller, animated: true, completion: nil)
```

<img width="414" alt="Screen Shot 2021-03-17 at 10 38 03" src="https://user-images.githubusercontent.com/1519494/111432186-bf600e00-870d-11eb-8da8-021bd1c10329.png">

I call another viewController with the plus button.
```
      let mViewcontroller = destination(.createAccount) as! NewAccountViewController
        //mViewcontroller.modalPresentationStyle = .fullScreen
        self.present(mViewcontroller, animated: true, completion: nil)
```

When returning from the newaccount screen with dismiss, the bottom sheet screen looks like this:
<img width="413" alt="Screen Shot 2021-03-17 at 10 29 41" src="https://user-images.githubusercontent.com/1519494/111432875-a4da6480-870e-11eb-9337-5d8c5792803b.png">

It's okay if I don't call it with fullscreen. But when calling as fullscreen, bottomsheet view width changes and viewDidDisappear method is called.
I could not find the reason, I hope you can help.
Thanks a lot.

**Comment by sgmaturano** [comment]
Same error.

**Comment by sgmaturano** [comment]
@osmansoykan I fixed it using `overfullscreen`

**Comment by osanoj** [comment]
Thanks for the help @sgmaturano 👍

**Comment by oskarko** [comment]
The issue is not fixed yet at all, why do you close it @osanoj ?
I'm presenting a video-reward from AdMob SDK and I cannot set up the modalPresentationStyle property.

Any other alternative to avoid this glitch? Any real fix?

Thank you!

**Comment by osanoj** [comment]
> The issue is not fixed yet at all, why do you close it @osanoj ?
> I'm presenting a video-reward from AdMob SDK and I cannot set up the modalPresentationStyle property.
> 
> Any other alternative to avoid this glitch? Any real fix?
> 
> Thank you!

Well, with a solution offered and no furter response in a while there is no reason to keep it open?

Are you having a similar issue @oskarko? Please create a new issue if you think it is a bug in the code, a link to a sample project where we can reproduce the problem will help you get more attention and quicker feedback.

_Please note though that we provide this project to share what we are using in our apps and not to solve everyones need. If the problem you are having is not because of a bug but rather a missing feature or a different use-case (i.e. only an issue when using AdMob videos) I would suggest trying to solve it yourself and submitting a PR instead._

**Comment by oskarko** [comment]
Here you have @osanoj https://github.com/finn-no/BottomSheet/issues/50
